/// <reference path="../../worker-configuration.d.ts" />

// Generated by `bun run cf-typegen` from the root Wrangler configuration.
// This alias keeps package consumers independent of the generated file path.
export type CloudflareEnv = Env;
